initial prototype for MLR model, engineering features, and doing train test split

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.metrics import root_mean_squared_error, mean_absolute_percentage_error
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, FunctionTransformer
import pickle as pkl
from scipy import stats
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor

In [2]:
# import the data
df = pd.read_csv('../data/processed/hourly_usage_cleaned.csv')

In [3]:
# assign multiindex
df.set_index(['datetime', 'client_id'], inplace=True)

In [4]:
# create lagged features
df['lag_1hr'] = df.groupby(level='client_id')['hourly_usage_kwh'].shift(1)
df['lag_2hr'] = df.groupby(level='client_id')['hourly_usage_kwh'].shift(2)
df['lag_6hr'] = df.groupby(level='client_id')['hourly_usage_kwh'].shift(6)
df['lag_1dy'] = df.groupby(level='client_id')['hourly_usage_kwh'].shift(24)
df['lag_1wk'] = df.groupby(level='client_id')['hourly_usage_kwh'].shift(7*24)


# fine to do before train test split as would have this at inference
df['rolling_mean_1dy'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24).mean())
df['rolling_mean_1wk'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24*7).mean())

# get the rolling max, min and standard deviation (for volatility)
df['rolling_max_1dy'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24).max())
df['rolling_max_1wk'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24*7).max())

df['rolling_min_1dy'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24).min())
df['rolling_min_1wk'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24*7).min())

df['rolling_std_1dy'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24).std())
df['rolling_std_1wk'] = df.groupby(level='client_id')['hourly_usage_kwh'].transform(lambda x: x.rolling(window=24*7).std())

In [5]:
# and now get features for the hour, day of week and month. using cyclical encoding, 
# to avoid misinterpration of values (e.g., 1 and 12 for months are far numerically but similar with 
# regards to being winter)
df['hour'] = np.sin(2*np.pi*pd.to_datetime(df.index.get_level_values('datetime')).hour/24)
df['day_of_week'] = np.sin(2*np.pi*pd.to_datetime(df.index.get_level_values('datetime')).dayofweek/7)
df['month'] = np.sin(2*np.pi*pd.to_datetime(df.index.get_level_values('datetime')).month/12)

In [6]:
# remove nans where no feature
df.dropna(inplace=True)

df.xs(4, level='client_id').tail(50)

,hourly_usage_kwh,lag_1hr,lag_2hr,lag_6hr,lag_1dy,lag_1wk,rolling_mean_1dy,rolling_mean_1wk,rolling_max_1dy,rolling_max_1wk,rolling_min_1dy,rolling_min_1wk,rolling_std_1dy,rolling_std_1wk,hour,day_of_week,month
datetime,,,,,,,,,,,,,,,,,
2014-12-29 23:00:00,205.284553,234.247967,223.069106,110.264228,171.747967,203.760163,145.748645,146.528988,238.821138,251.524390,103.150407,71.646341,45.727452,40.907181,-2.588190e-01,0.000000,-2.449294e-16
2014-12-30 00:00:00,176.321138,205.284553,234.247967,174.796748,150.406504,173.780488,146.828421,146.544111,238.821138,251.524390,103.150407,71.646341,46.146269,40.917784,0.000000e+00,0.781831,-2.449294e-16
2014-12-30 01:00:00,154.471545,176.321138,205.284553,236.280488,132.621951,146.849593,147.738821,146.589479,238.821138,251.524390,103.150407,71.646341,46.069276,40.922350,2.588190e-01,0.781831,-2.449294e-16
2014-12-30 02:00:00,137.195122,154.471545,176.321138,238.821138,121.443089,122.459350,148.395156,146.677192,238.821138,251.524390,103.150407,71.646341,45.789720,40.886096,5.000000e-01,0.781831,-2.449294e-16
2014-12-30 03:00:00,121.443089,137.195122,154.471545,223.069106,116.361789,110.772358,148.606877,146.740708,238.821138,251.524390,103.150407,71.646341,45.646689,40.838245,7.071068e-01,0.781831,-2.449294e-16
2014-12-30 04:00:00,116.361789,121.443089,137.195122,234.247967,103.150407,108.739837,149.157351,146.786077,238.821138,251.524390,108.231707,71.646341,45.151652,40.799991,8.660254e-01,0.781831,-2.449294e-16
2014-12-30 05:00:00,111.788618,116.361789,121.443089,205.284553,108.739837,112.296748,149.284383,146.783053,238.821138,251.524390,108.231707,71.646341,45.037138,40.802582,9.659258e-01,0.781831,-2.449294e-16
2014-12-30 06:00:00,112.296748,111.788618,116.361789,176.321138,110.264228,109.247967,149.369072,146.801200,238.821138,251.524390,108.231707,71.646341,44.962423,40.786463,1.000000e+00,0.781831,-2.449294e-16
2014-12-30 07:00:00,128.556911,112.296748,111.788618,154.471545,123.475610,121.951220,149.580793,146.840520,238.821138,251.524390,108.231707,71.646341,44.847009,40.765542,9.659258e-01,0.781831,-2.449294e-16
2014-12-30 08:00:00,115.345528,128.556911,112.296748,137.195122,108.231707,110.772358,149.877202,146.867741,238.821138,251.524390,110.264228,71.646341,44.584578,40.742833,8.660254e-01,0.781831,-2.449294e-16
2014-12-30 09:00:00,120.426829,115.345528,128.556911,121.443089,121.951220,105.691057,149.813686,146.955454,238.821138,251.524390,110.264228,71.646341,44.627157,40.669451,7.071068e-01,0.781831,-2.449294e-16
2014-12-30 10:00:00,112.296748,120.426829,115.345528,116.361789,120.934959,115.853659,149.453760,146.934282,238.821138,251.524390,110.264228,71.646341,44.904170,40.686662,5.000000e-01,0.781831,-2.449294e-16
2014-12-30 11:00:00,129.065041,112.296748,120.426829,111.788618,126.016260,117.886179,149.580793,147.000823,238.821138,251.524390,110.264228,71.646341,44.839249,40.647994,2.588190e-01,0.781831,-2.449294e-16
2014-12-30 12:00:00,137.703252,129.065041,112.296748,112.296748,126.524390,136.686992,150.046579,147.006872,238.821138,251.524390,110.264228,71.646341,44.646978,40.646525,1.224647e-16,0.781831,-2.449294e-16
2014-12-30 13:00:00,136.686992,137.703252,129.065041,128.556911,141.260163,125.508130,149.856030,147.073413,238.821138,251.524390,110.264228,71.646341,44.695840,40.620261,-2.588190e-01,0.781831,-2.449294e-16
2014-12-30 14:00:00,120.934959,136.686992,137.703252,115.345528,125.000000,135.162602,149.686653,146.988724,238.821138,251.524390,110.264228,71.646341,44.801705,40.660055,-5.000000e-01,0.781831,-2.449294e-16
2014-12-30 15:00:00,111.788618,120.934959,136.686992,120.426829,118.394309,121.443089,149.411416,146.931257,238.821138,251.524390,110.264228,71.646341,45.022055,40.703176,-7.071068e-01,0.781831,-2.449294e-16
2014-12-30 16:00:00,106.707317,111.788618,120.934959,112.296748,120.426829,129.065041,148.839770,146.798176,238.821138,251.524390,106.707317,71.646341,45.490733,40.798379,-8.660254e-01,0.781831,-2.449294e-16
2014-12-30 17:00:00,112.804878,106.707317,111.788618,129.065041,110.264228,139.227642,148.945630,146.640897,238.821138,251.524390,106.707317,71.646341,45.399928,40.878589,-9.659258e-01,0.781831,-2.449294e-16
2014-12-30 18:00:00,141.260163,112.804878,106.707317,137.703252,174.796748,171.239837,147.548272,146.462447,238.821138,251.524390,106.707317,71.646341,45.084680,40.835977,-1.000000e+00,0.781831,-2.449294e-16
2014-12-30 19:00:00,227.642276,141.260163,112.804878,136.686992,236.280488,234.756098,147.188347,146.420103,238.821138,251.524390,106.707317,71.646341,44.374389,40.747466,-9.659258e-01,0.781831,-2.449294e-16
2014-12-30 20:00:00,261.686992,227.642276,141.260163,120.934959,238.821138,250.508130,148.141091,146.486643,261.686992,261.686992,106.707317,71.646341,46.616182,40.927192,-8.660254e-01,0.781831,-2.449294e-16
2014-12-30 21:00:00,227.642276,261.686992,227.642276,111.788618,223.069106,246.443089,148.331640,146.374734,261.686992,261.686992,106.707317,71.646341,46.943969,40.677179,-7.071068e-01,0.781831,-2.449294e-16
2014-12-30 22:00:00,239.329268,227.642276,261.686992,106.707317,234.247967,235.264228,148.543360,146.398931,261.686992,261.686992,106.707317,71.646341,47.357938,40.731544,-5.000000e-01,0.781831,-2.449294e-16
2014-12-30 23:00:00,208.841463,239.329268,227.642276,112.804878,205.284553,226.117886,148.691565,146.296095,261.686992,261.686992,106.707317,71.646341,47.548411,40.550477,-2.588190e-01,0.781831,-2.449294e-16
2014-12-31 00:00:00,185.467480,208.841463,239.329268,141.260163,176.321138,183.943089,149.072663,146.305168,261.686992,261.686992,106.707317,71.646341,47.815392,40.559121,0.000000e+00,0.974928,-2.449294e-16
2014-12-31 01:00:00,165.650407,185.467480,208.841463,227.642276,154.471545,144.817073,149.538449,146.429176,261.686992,261.686992,106.707317,71.646341,47.924595,40.586383,2.588190e-01,0.974928,-2.449294e-16
2014-12-31 02:00:00,139.227642,165.650407,185.467480,261.686992,137.195122,136.178862,149.623137,146.447324,261.686992,261.686992,106.707317,71.646341,47.903626,40.582454,5.000000e-01,0.974928,-2.449294e-16
2014-12-31 03:00:00,113.821138,139.227642,165.650407,227.642276,121.443089,111.280488,149.305556,146.462447,261.686992,261.686992,106.707317,71.646341,48.123332,40.569742,7.071068e-01,0.974928,-2.449294e-16
2014-12-31 04:00:00,101.117886,113.821138,139.227642,239.329268,116.361789,109.756098,148.670393,146.411029,261.686992,261.686992,101.117886,71.646341,48.674493,40.621983,8.660254e-01,0.974928,-2.449294e-16
2014-12-31 05:00:00,99.593496,101.117886,113.821138,208.841463,111.788618,106.707317,148.162263,146.368685,261.686992,261.686992,99.593496,71.646341,49.137705,40.667300,9.659258e-01,0.974928,-2.449294e-16
2014-12-31 06:00:00,102.134146,99.593496,101.117886,185.467480,112.296748,112.296748,147.738821,146.308193,261.686992,261.686992,99.593496,71.646341,49.502645,40.725801,1.000000e+00,0.974928,-2.449294e-16
2014-12-31 07:00:00,108.231707,102.134146,99.593496,165.650407,128.556911,113.821138,146.891938,146.274923,261.686992,261.686992,99.593496,71.646341,50.016270,40.754772,9.659258e-01,0.974928,-2.449294e-16
2014-12-31 08:00:00,111.788618,108.231707,102.134146,139.227642,115.345528,100.101626,146.743733,146.344488,261.686992,261.686992,99.593496,71.646341,50.118974,40.685401,8.660254e-01,0.974928,-2.449294e-16
2014-12-31 09:00:00,113.313008,111.788618,108.231707,113.821138,120.426829,117.378049,146.447324,146.320291,261.686992,261.686992,99.593496,71.646341,50.302084,40.703936,7.071068e-01,0.974928,-2.449294e-16
2014-12-31 10:00:00,137.703252,113.313008,111.788618,101.117886,112.296748,128.048780,147.505928,146.377758,261.686992,261.686992,99.593496,71.646341,49.817141,40.684796,5.000000e-01,0.974928,-2.449294e-16
2014-12-31 11:00:00,136.686992,137.703252,113.313008,99.593496,129.065041,142.276423,147.823509,146.344488,261.686992,261.686992,99.593496,71.646341,49.718668,40.690455,2.588190e-01,0.974928,-2.449294e-16
2014-12-31 12:00:00,155.487805,136.686992,137.703252,102.134146,137.703252,166.158537,148.564533,146.280972,261.686992,261.686992,99.593496,71.646341,49.693801,40.667663,1.224647e-16,0.974928,-2.449294e-16
2014-12-31 13:00:00,171.239837,155.487805,136.686992,108.231707,136.686992,177.337398,150.004234,146.244677,261.686992,261.686992,99.593496,71.646341,49.835052,40.642493,-2.588190e-01,0.974928,-2.449294e-16
2014-12-31 14:00:00,146.341463,171.239837,155.487805,111.788618,120.934959,138.719512,151.062839,146.290045,261.686992,261.686992,99.593496,71.646341,49.459137,40.638296,-5.000000e-01,0.974928,-2.449294e-16
2014-12-31 15:00:00,137.703252,146.341463,171.239837,113.313008,111.788618,137.195122,152.142615,146.293070,261.686992,261.686992,99.593496,71.646341,48.843484,40.637634,-7.071068e-01,0.974928,-2.449294e-16
2014-12-31 16:00:00,139.227642,137.703252,146.341463,137.703252,106.707317,130.081301,153.497629,146.347513,261.686992,261.686992,99.593496,71.646341,47.971523,40.621909,-8.660254e-01,0.974928,-2.449294e-16
2014-12-31 17:00:00,160.569106,139.227642,137.703252,136.686992,112.804878,136.178862,155.487805,146.492693,261.686992,261.686992,99.593496,71.646341,47.194412,40.628933,-9.659258e-01,0.974928,-2.449294e-16
2014-12-31 18:00:00,176.829268,160.569106,139.227642,155.487805,141.260163,185.975610,156.969851,146.438250,261.686992,261.686992,99.593496,71.646341,47.286594,40.581810,-1.000000e+00,0.974928,-2.449294e-16
2014-12-31 19:00:00,209.349593,176.829268,160.569106,171.239837,227.642276,204.776423,156.207656,146.465471,261.686992,261.686992,99.593496,71.646341,46.233626,40.622689,-9.659258e-01,0.974928,-2.449294e-16
2014-12-31 20:00:00,205.284553,209.349593,176.829268,146.341463,261.686992,195.630081,153.857554,146.522938,239.329268,261.686992,99.593496,71.646341,41.866095,40.699413,-8.660254e-01,0.974928,-2.449294e-16
2014-12-31 21:00:00,178.353659,205.284553,209.349593,137.703252,227.642276,175.813008,151.803862,146.538061,239.329268,261.686992,99.593496,71.646341,39.214216,40.710832,-7.071068e-01,0.974928,-2.449294e-16
2014-12-31 22:00:00,162.601626,178.353659,205.284553,139.227642,239.329268,166.158537,148.606877,146.516889,209.349593,261.686992,99.593496,71.646341,34.627807,40.701491,-5.000000e-01,0.974928,-2.449294e-16
2014-12-31 23:00:00,157.520325,162.601626,178.353659,160.569106,208.841463,167.174797,146.468496,146.459422,209.349593,261.686992,99.593496,71.646341,32.249338,40.678959,-2.588190e-01,0.974928,-2.449294e-16
2015-01-01 00:00:00,168.699187,157.520325,162.601626,176.829268,185.467480,160.060976,145.769817,146.510840,209.349593,261.686992,99.593496,71.646341,31.541569,40.701707,0.000000e+00,0.433884,5.000000e-01

In [7]:
# for now just do a super naive (non random split) of time series data - use earlier data for testing,
# and latter for training (use Time Series Split afterwards). 

# just filter using datetime directly

# define train proportion
train_proportion = 0.65
# first get timestamps for start and end time
start_date = pd.to_datetime(df.index.get_level_values('datetime')).min()
end_date = pd.to_datetime(df.index.get_level_values('datetime')).max()
# then the total time elapsed timedelta
tot_time_elasped = end_date - start_date
# multiply by train proportion and add to start date to get cutoff point
cutoff_date = start_date + tot_time_elasped*train_proportion

# now use cutoff data to filter for test and train
df_train = df[pd.to_datetime(df.index.get_level_values('datetime')) < cutoff_date]
df_test = df[pd.to_datetime(df.index.get_level_values('datetime')) > cutoff_date]

print('\n train shape: ', df_train.shape)
print('\n test shape: ', df_test.shape)

# now split into target and features (train and validation) (#TODO: do proper hyperparameter grid search
# for the different type of models)
y_train = df_train['hourly_usage_kwh']
y_validate = df_test['hourly_usage_kwh']

X_train = df_train.drop(columns=['hourly_usage_kwh'])
X_validate = df_test.drop(columns=['hourly_usage_kwh'])



# delete redundant dataframes
del df_train
del df_test
del df

#NOTE: need to scale features before input into linear regression - to stop large dominating!

# need for stratification by client? or maybe not because have all the features on per client basis already
# should be able to get back

 train shape:  (5833986, 17)

 test shape:  (4297202, 17)

In [8]:
# save the training and validation data 

with open('../data/processed/X_train.csv', 'wb') as f:
    pkl.dump(X_train, f)

with open('../data/processed/y_train.csv', 'wb') as f:
    pkl.dump(y_train, f)

with open('../data/processed/X_validate.csv', 'wb') as f:
    pkl.dump(X_validate, f)

with open('../data/processed/y_validate.csv', 'wb') as f:
    pkl.dump(y_validate, f)

In [ ]:
# try normalising data on a per client basis (will incorporate into an sklearn pipeline), and create additional
# version of variable (rolling mean in week) scaled globally to encode magnitude

# set up the scalar
scaler_global = StandardScaler()

# going to need to use a for loop to first fit a transformer on training data, 
# then transform both the training and testing

# for each column in X_train, need to store the fitted scaler (although would need transform)
# X_train_scalers = X_train.groupby(level='client_id').agg(lambda x: StandardScaler().fit(x.values.reshape(1, -1)))

# create empty list for scalars for each client (need to figure out datatype standardscaler to put in array)
scalers_per_client = []

# create empty list of dataframes, so csan append them
X_train_normalised_per_client = []
X_test_normalised_per_client = []

# get client_ids
# print(X_test.index.get_level_values('client_id').unique().difference(X_train.index.get_level_values('client_id')))

#NOTE: have clients in testing data that not the training data 
# (because of clean time split, and customer starting later)
# throws a spanner in the works for per client normalisation...

# # Now for each client_id, extract the appropriate scalar and use to transform both 
# for i in client_ids:
    
#     # get data for client for train and test
#     client_X_train = X_train.xs(i, level='client_id')
#     client_X_test = X_test.xs(i, level='client_id')
    
#     # fit standard scaler to client data
#     fitted_scaler = StandardScaler().fit(client_X_train)

#     # then use to transform training data, indexing into appropriate client
#     # X_train_normalised_per_client.xs((slice(None), i), level='client_id') = scalars_per_client[i].transform(X_train.xs(i, level='client_id'))
#     client_X_train_normalised = fitted_scaler.transform(client_X_train)

#     # and now also use to transform the testing data
#     # X_test_normalised_per_client.xs((slice(None), i), level='client_id') = scalars_per_client[i].transform(X_test.xs(i, level='client_id'))
#     client_X_test_normalised = fitted_scaler.transform(client_X_test)


#     print('\n client X_test: ', client_X_test.shape)
#     print('\n client X_test normalised: ', client_X_test_normalised.shape)
#     # # need to convert to dataframes because scaling outputs an array
#     client_X_train_normalised_df = pd.DataFrame(client_X_train_normalised, index=client_X_train.index, columns=client_X_train.columns)
#     client_X_test_normalised_df = pd.DataFrame(client_X_test_normalised, index=client_X_test.index, columns=client_X_test.columns)

#     print('\n client X_test normalised df: ', client_X_test_normalised_df.shape)
#     # and append to lists
#     scalers_per_client.append(fitted_scaler)
#     X_train_normalised_per_client.append(client_X_train_normalised_df)
#     X_test_normalised_per_client.append(client_X_test_normalised_df)

# # # check where size discrep occurs
# print(X_train.shape)
# print(sum(len(df) for df in X_train_normalised_per_client))

# now just concatenate list of dataframes.
# # because client id key was removed during .xs() extraction, add back in here
# X_train_normalised_per_client = pd.concat(X_train_normalised_per_client, keys=client_ids)
# X_test_normalised_per_client = pd.concat(X_test_normalised_per_client, keys=client_ids)

# now can use appropriate scaler somehow to transform scaling data
# X_train_normalised = X_train.groupby(level='client_id').apply(lambda x: )



# if using skleanr pipelines, would need to implement a custom transformer object to achieve per client normalisation

# easiest way may just be a column transformer (but doesn't save the mean and std needed)

# to get normalised target (rudimentary), can use transform with standardisation function. but need to reshape to 2D,
# for compatibility with scaler method. then need to ravel for compatibility with .transform()
# y_train_normalised  = y_train.groupby(level='client_id').transform(lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).ravel())
# y_test_normalised  = y_test.groupby(level='client_id').transform(lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).ravel())

# X_train_normalised  = X_train.groupby(level='client_id').transform(lambda x: scaler.fit_transform(x))
# X_test_normalised  = X_test.groupby(level='client_id').transform(lambda x: scaler.fit_transform(x))

# TODO: get client-based normalisation for features
# then add global_scaled features to capture magnitude - use a rolling mean of past week (because want to keep context window the same)

# df_normalised_per_client = df.groupby(level='client_id').apply(lambda g: scaler.fit_transform(g))

Index([ 12,  39,  41, 106, 107, 108, 109, 110, 111, 112, 113, 115, 116, 117,
       120, 121, 122, 133, 160, 165, 178, 179, 181, 186, 289, 305, 322, 337],
      dtype='int64', name='client_id')

In [ ]:
# # save normalised features to csv
# X_train_normalised_per_client.to_csv('../data/processed/X_train_normalised_per_client.csv', index=False)
# X_test_normalised_per_client.to_csv('../data/processed/X_test_normalised_per_client.csv', index=False)

# # and scalars to pkl
# with open('../data/processed/scalars.pkl', 'wb') as f:
#     pkl.dump(scalers_per_client, f)

# del scalers_per_client

Try global normalisation for now

In [10]:
scaler_global = StandardScaler()
# fit the global scaler
scaler_global.fit(X_train)
# and use to transform both the training and testing data
X_train_normalised = pd.DataFrame(scaler_global.transform(X_train), index=X_train.index, columns=X_train.columns)

# save the global scaler, which will use on validation data
with open('../data/processed/scaler_global.pkl', 'wb') as f:
    pkl.dump(scaler_global, f)

# X_test_normalised = pd.DataFrame(scaler_global.transform(X_test), index=X_test.index, columns=X_test.columns)

In [44]:
X_train_normalised.head(50)

,,lag_1hr,lag_2hr,lag_6hr,lag_1dy,lag_1wk,rolling_mean_1dy,rolling_mean_1wk,rolling_max_1dy,rolling_max_1wk,rolling_min_1dy,rolling_min_1wk,rolling_std_1dy,rolling_std_1wk,hour,day_of_week,month
datetime,client_id,,,,,,,,,,,,,,,,
2012-01-08 01:00:00,1,-0.429025,-0.423253,-0.415570,-0.436622,-0.437716,-0.450356,-0.453460,-0.469863,-0.473056,-0.372840,-0.398642,-0.454550,-0.458008,0.365995,-1.106743,0.564922
2012-01-08 02:00:00,1,-0.435453,-0.429039,-0.421999,-0.436300,-0.437070,-0.450342,-0.453460,-0.469863,-0.473056,-0.372840,-0.398642,-0.454607,-0.458008,0.707089,-1.106743,0.564922
2012-01-08 03:00:00,1,-0.435774,-0.435467,-0.421999,-0.436622,-0.437716,-0.450328,-0.453458,-0.469863,-0.473056,-0.372840,-0.398642,-0.454666,-0.458016,0.999994,-1.106743,0.564922
2012-01-08 04:00:00,1,-0.436096,-0.435788,-0.430999,-0.436622,-0.437070,-0.450300,-0.453458,-0.469863,-0.473056,-0.372840,-0.398642,-0.454782,-0.458016,1.224747,-1.106743,0.564922
2012-01-08 05:00:00,1,-0.435774,-0.436110,-0.423285,-0.436300,-0.437393,-0.450285,-0.453456,-0.469863,-0.473056,-0.372840,-0.398642,-0.454839,-0.458023,1.366033,-1.106743,0.564922
2012-01-08 06:00:00,1,-0.435774,-0.435788,-0.429070,-0.436622,-0.437393,-0.450257,-0.453454,-0.469863,-0.473056,-0.372840,-0.398642,-0.454957,-0.458030,1.414223,-1.106743,0.564922
2012-01-08 07:00:00,1,-0.435774,-0.435788,-0.435499,-0.437265,-0.437070,-0.450215,-0.453456,-0.469863,-0.473056,-0.371309,-0.398642,-0.455147,-0.458023,1.366033,-1.106743,0.564922
2012-01-08 08:00:00,1,-0.436096,-0.435788,-0.435820,-0.435657,-0.437716,-0.450173,-0.453444,-0.469863,-0.473056,-0.371309,-0.398642,-0.455302,-0.458064,1.224747,-1.106743,0.564922
2012-01-08 09:00:00,1,-0.434489,-0.436110,-0.436142,-0.424400,-0.439330,-0.450201,-0.453361,-0.469863,-0.473056,-0.371309,-0.398642,-0.455360,-0.458173,0.999994,-1.106743,0.564922
2012-01-08 10:00:00,1,-0.424847,-0.434502,-0.435820,-0.424400,-0.436747,-0.450243,-0.453296,-0.469863,-0.473056,-0.371309,-0.398642,-0.455445,-0.458222,0.707089,-1.106743,0.564922
2012-01-08 11:00:00,1,-0.425168,-0.424860,-0.435820,-0.424722,-0.425770,-0.450074,-0.453272,-0.469863,-0.473056,-0.371309,-0.398642,-0.454922,-0.458144,0.365995,-1.106743,0.564922
2012-01-08 12:00:00,1,-0.420669,-0.425182,-0.435820,-0.423757,-0.432227,-0.450117,-0.453232,-0.469863,-0.473056,-0.371309,-0.398642,-0.455017,-0.458122,-0.000045,-1.106743,0.564922
2012-01-08 13:00:00,1,-0.424525,-0.420682,-0.436142,-0.421827,-0.435779,-0.450243,-0.453169,-0.469863,-0.473056,-0.371309,-0.398642,-0.455377,-0.458148,-0.366084,-1.106743,0.564922
2012-01-08 14:00:00,1,-0.424525,-0.424539,-0.434535,-0.430189,-0.439976,-0.450314,-0.453124,-0.469863,-0.473056,-0.371309,-0.398027,-0.455283,-0.458298,-0.707179,-1.106743,0.564922
2012-01-08 15:00:00,1,-0.431596,-0.424539,-0.424892,-0.433084,-0.432227,-0.450539,-0.453169,-0.469863,-0.473056,-0.374370,-0.398027,-0.454438,-0.458163,-1.000083,-1.106743,0.564922
2012-01-08 16:00:00,1,-0.438024,-0.431610,-0.425213,-0.423113,-0.429967,-0.450581,-0.453139,-0.469863,-0.473056,-0.374370,-0.398027,-0.454555,-0.458125,-1.224837,-1.106743,0.564922
2012-01-08 17:00:00,1,-0.423883,-0.438038,-0.420713,-0.424078,-0.439653,-0.450257,-0.453001,-0.469863,-0.473056,-0.374370,-0.397413,-0.453164,-0.458040,-1.366123,-1.106743,0.564922
2012-01-08 18:00:00,1,-0.416490,-0.423896,-0.424570,-0.422792,-0.430290,-0.450426,-0.452985,-0.469863,-0.473056,-0.374370,-0.397413,-0.453497,-0.458034,-1.414313,-1.106743,0.564922
2012-01-08 19:00:00,1,-0.426454,-0.416504,-0.424570,-0.415716,-0.426093,-0.451299,-0.453052,-0.470639,-0.473056,-0.374370,-0.397413,-0.455072,-0.457978,-1.366123,-1.106743,0.564922
2012-01-08 20:00:00,1,-0.435453,-0.426467,-0.431642,-0.422148,-0.437716,-0.451327,-0.452965,-0.470639,-0.473056,-0.374370,-0.397413,-0.455181,-0.458022,-1.224837,-1.106743,0.564922
2012-01-08 21:00:00,1,-0.422597,-0.435467,-0.438070,-0.422148,-0.433842,-0.451327,-0.452898,-0.470639,-0.473056,-0.374370,-0.397413,-0.455181,-0.457980,-1.000083,-1.106743,0.564922
2012-01-08 22:00:00,1,-0.421954,-0.422611,-0.423927,-0.431154,-0.423187,-0.451285,-0.452948,-0.470639,-0.473056,-0.374370,-0.397413,-0.455207,-0.458045,-0.707179,-1.106743,0.564922
2012-01-08 23:00:00,1,-0.429989,-0.421968,-0.416535,-0.423435,-0.429644,-0.451229,-0.452908,-0.470639,-0.473056,-0.374370,-0.397413,-0.455002,-0.457976,-0.366084,-1.106743,0.564922
2012-01-09 00:00:00,1,-0.421954,-0.430003,-0.426499,-0.429224,-0.432227,-0.451327,-0.452910,-0.470639,-0.473056,-0.374370,-0.397413,-0.454957,-0.457973,-0.000045,-0.000783,0.564922
2012-01-09 01:00:00,1,-0.431275,-0.421968,-0.435499,-0.435657,-0.438039,-0.451355,-0.452906,-0.470639,-0.473056,-0.374370,-0.397413,-0.454859,-0.457990,0.365995,-0.000783,0.564922
2012-01-09 02:00:00,1,-0.436096,-0.431288,-0.422642,-0.435979,-0.437716,-0.451355,-0.452902,-0.470639,-0.473056,-0.374370,-0.397413,-0.454859,-0.458006,0.707089,-0.000783,0.564922
2012-01-09 03:00:00,1,-0.435774,-0.436110,-0.421999,-0.436300,-0.438039,-0.451341,-0.452896,-0.470639,-0.473056,-0.374370,-0.397413,-0.454909,-0.458031,0.999994,-0.000783,0.564922
2012-01-09 04:00:00,1,-0.435774,-0.435788,-0.430035,-0.435979,-0.437716,-0.451341,-0.452892,-0.470639,-0.473056,-0.374370,-0.397413,-0.454909,-0.458047,1.224747,-0.000783,0.564922
2012-01-09 05:00:00,1,-0.435774,-0.435788,-0.421999,-0.435979,-0.438039,-0.451341,-0.452886,-0.470639,-0.473056,-0.374370,-0.397413,-0.454909,-0.458071,1.366033,-0.000783,0.564922
2012-01-09 06:00:00,1,-0.435774,-0.435788,-0.431320,-0.435979,-0.438361,-0.451341,-0.452878,-0.470639,-0.473056,-0.374370,-0.397413,-0.454909,-0.458105,1.414223,-0.000783,0.564922
2012-01-09 07:00:00,1,-0.435774,-0.435788,-0.436142,-0.436300,-0.438684,-0.451341,-0.452869,-0.470639,-0.473056,-0.374370,-0.397413,-0.454909,-0.458140,1.366033,-0.000783,0.564922
2012-01-09 08:00:00,1,-0.436096,-0.435788,-0.435820,-0.434692,-0.438684,-0.451299,-0.452845,-0.470639,-0.473056,-0.374370,-0.397413,-0.455016,-0.458229,1.224747,-0.000783,0.564922
2012-01-09 09:00:00,1,-0.433525,-0.436110,-0.435820,-0.425043,-0.428030,-0.451271,-0.452829,-0.470639,-0.473056,-0.374370,-0.397413,-0.454943,-0.458205,0.999994,-0.000783,0.564922
2012-01-09 10:00:00,1,-0.424204,-0.433538,-0.435820,-0.425365,-0.424802,-0.451032,-0.452805,-0.470639,-0.473056,-0.374370,-0.397413,-0.454083,-0.458120,0.707089,-0.000783,0.564922
2012-01-09 11:00:00,1,-0.419704,-0.424218,-0.435820,-0.420862,-0.425125,-0.451018,-0.452782,-0.470639,-0.473056,-0.374370,-0.397413,-0.454020,-0.458048,0.365995,-0.000783,0.564922
2012-01-09 12:00:00,1,-0.420347,-0.419718,-0.435820,-0.424722,-0.421573,-0.451018,-0.452809,-0.470639,-0.473056,-0.374370,-0.397413,-0.454020,-0.458128,-0.000045,-0.000783,0.564922
2012-01-09 13:00:00,1,-0.424525,-0.420361,-0.436142,-0.424722,-0.421896,-0.450989,-0.452829,-0.470639,-0.473056,-0.374370,-0.397413,-0.453949,-0.458193,-0.366084,-0.000783,0.564922
2012-01-09 14:00:00,1,-0.423883,-0.424539,-0.433570,-0.431798,-0.426093,-0.450666,-0.452825,-0.470639,-0.473056,-0.374370,-0.397413,-0.453784,-0.458185,-0.707179,-0.000783,0.564922
2012-01-09 15:00:00,1,-0.424204,-0.423896,-0.424249,-0.438230,-0.420282,-0.449891,-0.452833,-0.470639,-0.473056,-0.371309,-0.397413,-0.454115,-0.458221,-1.000083,-0.000783,0.564922
2012-01-09 16:00:00,1,-0.420347,-0.424218,-0.419749,-0.424078,-0.425125,-0.450300,-0.452892,-0.470639,-0.473056,-0.371309,-0.397413,-0.454039,-0.458217,-1.224837,-0.000783,0.564922
2012-01-09 17:00:00,1,-0.433203,-0.420361,-0.420392,-0.416681,-0.418990,-0.451088,-0.452997,-0.473224,-0.473056,-0.371309,-0.397413,-0.455422,-0.458347,-1.366123,-0.000783,0.564922
2012-01-09 18:00:00,1,-0.434489,-0.433217,-0.424570,-0.426651,-0.432550,-0.450905,-0.452940,-0.473224,-0.473056,-0.371309,-0.397413,-0.454953,-0.458295,-1.414313,-0.000783,0.564922
2012-01-09 19:00:00,1,-0.422276,-0.434502,-0.423927,-0.435657,-0.429644,-0.450018,-0.452857,-0.469605,-0.473056,-0.371309,-0.397413,-0.453460,-0.458008,-1.366123,-0.000783,0.564922
2012-01-09 20:00:00,1,-0.415205,-0.422289,-0.424249,-0.422792,-0.438039,-0.449976,-0.452762,-0.469605,-0.473056,-0.371309,-0.397413,-0.453332,-0.458049,-1.224837,-0.000783,0.564922
2012-01-09 21:00:00,1,-0.421633,-0.415218,-0.420392,-0.422148,-0.431259,-0.450328,-0.452762,-0.469605,-0.473056,-0.371309,-0.397413,-0.453740,-0.458049,-1.000083,-0.000783,0.564922
2012-01-09 22:00:00,1,-0.429989,-0.421646,-0.433249,-0.430189,-0.430613,-0.450271,-0.452758,-0.469605,-0.473056,-0.371309,-0.397413,-0.453768,-0.458050,-0.707179,-0.000783,0.564922
2012-01-09 23:00:00,1,-0.428704,-0.430003,-0.434535,-0.422148,-0.434810,-0.450271,-0.452685,-0.469605,-0.473056,-0.371309,-0.397413,-0.453768,-0.458030,-0.366084,-0.000783,0.564922
2012-01-10 00:00:00,1,-0.421954,-0.428717,-0.422320,-0.431476,-0.430936,-0.450271,-0.452695,-0.469605,-0.473056,-0.371309,-0.397413,-0.453768,-0.458018,-0.000045,1.105178,0.564922
2012-01-10 01:00:00,1,-0.431275,-0.421968,-0.415249,-0.436300,-0.437716,-0.450257,-0.452691,-0.469605,-0.473056,-0.371309,-0.397413,-0.453823,-0.458035,0.365995,1.105178,0.564922
2012-01-10 02:00:00,1,-0.435774,-0.431288,-0.421677,-0.435979,-0.438039,-0.450257,-0.452685,-0.469605,-0.473056,-0.371309,-0.397413,-0.453823,-0.458060,0.707089,1.105178,0.564922

In [ ]:
# for now could use Sklearn pipelines when dealing with sklearn models



# set up dictionary of models - for now just OLS and elastic net
model_dict = {
                'OLS': {'pipeline': Pipeline([('scale', StandardScaler()), ('clf', LinearRegression())]),
                        },
                'elastic_net': {'pipeline': Pipeline([('scale', StandardScaler()), ('clf', ElasticNet())]),
                                },
                
                'XGBoost': {Pipeline([('scale', StandardScaler()), ('clf', XGBRegressor())]),
                            },
              }

# # fit the models and predict using traininh data (no cross validation for now)
# for model_name, config in model_dict.items():

#     # if model_name != 'rgr_elastic':
#     #   continue
#     print('\n model: ', model_name)

#     # fit the model to training
#     config['model_object'].fit(X_train_normalised, y_train)

#     print('\n model fitted')

In [ ]:
# Do grid search with training data

# set up parameter grids
# dummy grid for OLS as no params to tune
model_dict['OLS']['param_grid'] = {'fit_intercept': True}

# for elastic net
model_dict['elastic_net']['param_grid']  = {'alpha': stats.loguniform(1e-2, 1e1),
                                            'l1_ratio': stats.uniform()}

# for XGBoost
model_dict['xgb']['param_grid'] = {'learning_rate': stats.loguniform(0.01, 1), 
                            'n_estimators': np.linspace(100, 2000, 10, dtype=np.int64),
                            'max_depth': np.linspace(2, 20, 10, dtype=np.int64), 
                            'gamma': np.linspace(0, 5, 6, dtype=np.float64),
                            'subsample': np.linspace(0.1, 1, 10, dtype=np.float64),
                            'colsample_bytree': np.linspace(0.1, 1, 10, dtype=np.float64),
                            'reg_alpha': np.linspace(0, 1, 11, dtype=np.float64),
                            'reg_lambda': np.linspace(0, 1, 11, dtype=np.float64),   
    }





# need to reorder training data, so that client Id is outer index. This way, when splitting 
# using number of rows (as time series split does), would then automatically 
X_train_normalised_reordered = X_train_normalised.sort_index(level='datetime')
y_train_reordered = y_train.sort_index(level='datetime')

# # X_train_normalised_reordered.head(50)
# y_train_reordered.head(50)
# set up time series splitter object
tscv = TimeSeriesSplit(n_splits=5)

# # TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None)
# for i, (train_index, test_index) in enumerate(tscv.split(X_train_normalised)):
#     print(f"Fold {i}:")
#     print(f"  Train: index={train_index}")
#     print(f"  Train: index shape={train_index.shape}")
#     print(f"  Test:  index={test_index}")
#     print(f"  Test:  index shape={test_index.shape}")
for model_name, config in model_dict.items():

    print(f'\n model to fit: {model_name}')

    # set up the random search object
    rgr = RandomizedSearchCV(estimator=config['model_object'],
                              param_distributions=config['param_grid'], cv=tscv, 
                              scoring='neg_root_mean_squared_error', random_state=42)
    
    # fit the random search CV to the data
    rgr.fit(X=X_train_normalised_reordered, y=y_train_reordered)

    print(f'\n fitted')

    # save the model
    with open(f'../models/{model_name}.pkl', 'wb') as f:
        pkl.dump(rgr, f)

    print(f'\n saved')

c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 1 is smaller than n_iter=10. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.509e+09, tolerance: 1.029e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.886e+09, tolerance: 1.658e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.373e+09, tolerance: 2.339e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.938e+09, tolerance: 3.036e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.021e+09, tolerance: 3.933e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.777e+09, tolerance: 1.029e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.440e+09, tolerance: 1.658e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.529e+09, tolerance: 2.339e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.275e+09, tolerance: 3.036e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.264e+09, tolerance: 3.933e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Flynn\anaconda3\envs\dataProjects1\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.227e+10, tolerance: 5.732e+08
  model = cd_fast.enet_coordinate_descent(

In [43]:
# import os
# for model_name in model_dict.keys():
#     size = os.path.getsize(f'../models/{model_name}.pkl')
#     print(f"{model_name}: {size} bytes")



# load in the models
for model_name, config in model_dict.items():

    if model_name == 'OLS':
        continue
    with open(f'../models/{model_name}.pkl', 'rb') as f:
            config['model_object'] = pkl.load(f)

In [56]:
# get coeffs of both models

df_coeffs = pd.DataFrame({'feature': model_dict['elastic_net']['model_object'].feature_names_in_, 
                        #   'coeff_lin_reg': model_dict['OLS']['model_object'].coef_,
                          'coeff_en': model_dict['elastic_net']['model_object'].best_estimator_.coef_,                      
                          })#.sort_values(by='coeff', key=abs)

pd.DataFrame(model_dict['elastic_net']['model_object'].cv_results_['params'])
# model_dict['elastic_net']['model_object'].best_index_
df_coeffs

             feature    coeff_en
0            lag_1hr  611.817676
1            lag_2hr -131.048020
2            lag_6hr  -64.595112
3            lag_1dy  238.369009
4            lag_1wk  255.218893
5   rolling_mean_1dy  127.195433
6   rolling_mean_1wk -129.332717
7    rolling_max_1dy   72.572417
8    rolling_max_1wk  -22.311029
9    rolling_min_1dy   44.159419
10   rolling_min_1wk  -13.484115
11   rolling_std_1dy   26.544240
12   rolling_std_1wk  -23.394848
13              hour   -0.518252
14       day_of_week    1.252498
15             month    0.537460

In [ ]:
# compute mean usage per client (in training set! 
# # probably fine but best to be consistent regarding data leakage)
# client_mean_usage = y_train.groupby(level='client_id').mean()


# # prediction loop

# for model_name, config in model_dict.items():
#     # run prediction (no cross validation for now)
#     y_pred = config['model_object'].predict(X_test_normalised)

#     print('\n prediction completed')


#     print('\n shape of y_pred: ', y_pred.shape)
#     print('\n shape of y_true: ', y_test.shape)
#     # compute rmse (try avoiding creation of dataframe at each timestep and just reference y_pred?)
#     config['rmse_per_client'] = pd.DataFrame({'y_true': y_test,
#                   'y_pred': y_pred}).groupby(level='client_id').apply(lambda g: root_mean_squared_error(y_true=g['y_true'], y_pred=g['y_pred']))

#     # get rmse normalised by the client mean usage
#     config['nrmse_per_client'] = config['rmse_per_client']/client_mean_usage

#     # and the mean nrmse
#     config['nrmse_per_mean'] = config['nrmse_per_client'].mean()

#     print('\n evalusation metrics done')

 prediction completed

 shape of y_pred:  (4297202,)

 shape of y_true:  (4297202,)

 evalusation metrics done

 prediction completed

 shape of y_pred:  (4297202,)

 shape of y_true:  (4297202,)

 evalusation metrics done

 prediction completed

 shape of y_pred:  (4297202,)

 shape of y_true:  (4297202,)

 evalusation metrics done

 prediction completed

 shape of y_pred:  (4297202,)

 shape of y_true:  (4297202,)

 evalusation metrics done

In [58]:
# X_train_normalised_reordered.describe().T

X_train.corr()

,lag_1hr,lag_2hr,lag_6hr,lag_1dy,lag_1wk,rolling_mean_1dy,rolling_mean_1wk,rolling_max_1dy,rolling_max_1wk,rolling_min_1dy,rolling_min_1wk,rolling_std_1dy,rolling_std_1wk,hour,day_of_week,month
lag_1hr,1.000000,0.991478,0.919683,0.983537,0.981634,0.950649,0.946909,0.941170,0.935328,0.898509,0.883864,0.785150,0.830252,-0.109921,0.001773,-0.024817
lag_2hr,0.991478,1.000000,0.939927,0.970444,0.968356,0.950939,0.946965,0.941248,0.935357,0.898635,0.883963,0.785218,0.830271,-0.111098,0.001516,-0.024861
lag_6hr,0.919683,0.939927,1.000000,0.896165,0.893498,0.951702,0.947115,0.941107,0.935349,0.898472,0.884205,0.785256,0.830243,-0.046834,0.000401,-0.024954
lag_1dy,0.983537,0.970444,0.896165,1.000000,0.984903,0.949832,0.947578,0.940233,0.935584,0.897689,0.884591,0.784336,0.830263,-0.101274,-0.002345,-0.025059
lag_1wk,0.981634,0.968356,0.893498,0.984903,1.000000,0.944409,0.946474,0.935757,0.934483,0.889816,0.883027,0.783486,0.830084,-0.101391,0.002300,-0.027316
rolling_mean_1dy,0.950649,0.950939,0.951702,0.949832,0.944409,1.000000,0.995578,0.988793,0.983070,0.944449,0.929456,0.824951,0.872523,-0.000020,-0.000547,-0.026255
rolling_mean_1wk,0.946909,0.946965,0.947115,0.947578,0.946474,0.995578,1.000000,0.986291,0.986930,0.936216,0.932677,0.827623,0.876197,-0.000018,0.000114,-0.027383
rolling_max_1dy,0.941170,0.941248,0.941107,0.940233,0.935757,0.988793,0.986291,1.000000,0.994235,0.893115,0.887877,0.892841,0.926333,-0.001295,-0.000883,-0.030144
rolling_max_1wk,0.935328,0.935357,0.935349,0.935584,0.934483,0.983070,0.986930,0.994235,1.000000,0.888945,0.885629,0.886484,0.929621,-0.000189,0.000124,-0.031593
rolling_min_1dy,0.898509,0.898635,0.898472,0.897689,0.889816,0.944449,0.936216,0.893115,0.888945,1.000000,0.955111,0.600771,0.682511,-0.000875,0.003565,-0.017195
rolling_min_1wk,0.883864,0.883963,0.884205,0.884591,0.883027,0.929456,0.932677,0.887877,0.885629,0.955111,1.000000,0.635449,0.678624,-0.000069,0.000653,-0.026886
rolling_std_1dy,0.785150,0.785218,0.785256,0.784336,0.783486,0.824951,0.827623,0.892841,0.886484,0.600771,0.635449,1.000000,0.978174,-0.000922,-0.004348,-0.039515
rolling_std_1wk,0.830252,0.830271,0.830243,0.830263,0.830084,0.872523,0.876197,0.926333,0.929621,0.682511,0.678624,0.978174,1.000000,-0.000032,0.000019,-0.037479
hour,-0.109921,-0.111098,-0.046834,-0.101274,-0.101391,-0.000020,-0.000018,-0.001295,-0.000189,-0.000875,-0.000069,-0.000922,-0.000032,1.000000,-0.000083,-0.000089
day_of_week,0.001773,0.001516,0.000401,-0.002345,0.002300,-0.000547,0.000114,-0.000883,0.000124,0.003565,0.000653,-0.004348,0.000019,-0.000083,1.000000,-0.002521
month,-0.024817,-0.024861,-0.024954,-0.025059,-0.027316,-0.026255,-0.027383,-0.030144,-0.031593,-0.017195,-0.026886,-0.039515,-0.037479,-0.000089,-0.002521,1.000000

In [91]:
for model_name, config in model_dict.items():
    
    print(f'\n mean nrmse for {model_name}: ', config['nrmse_per_mean'])

    # print('\n number of clients with nrmse below 0.1: ', config['nrmse_per_client'][config['nrmse_per_client'] < 0.1].shape)

    # print('\n number of clients with nrmse above 1: ', config['nrmse_per_client'][config['nrmse_per_client'] > 0.25].shape)

    print('\n clients above 1 nrmse: ', config['nrmse_per_client'][config['nrmse_per_client'] > 1.0])

 mean nrmse for rgr:  0.1143130702369497

 clients above 1 nrmse:  Series([], dtype: float64)

 mean nrmse for rgr_ridge:  0.11431291322163213

 clients above 1 nrmse:  Series([], dtype: float64)

 mean nrmse for rgr_lasso:  0.11358616979143099

 clients above 1 nrmse:  Series([], dtype: float64)

 mean nrmse for rgr_elastic:  0.11358616979143099

 clients above 1 nrmse:  Series([], dtype: float64)

In [90]:
# print(np.squeeze(rgr.coef_.shape))
# # print(rgr.intercept_)
# # print(rgr.feature_names_in_)

# create quick df of coeffs and feature names in
df_coeffs = pd.DataFrame({'feature': model_dict['rgr']['model_object'].feature_names_in_, 
                          'coeff_lin_reg': model_dict['rgr']['model_object'].coef_,
                          'coeff_ridge': model_dict['rgr_ridge']['model_object'].coef_,
                          'coeff_lasso': model_dict['rgr_lasso']['model_object'].coef_,
                          'coeff_en': model_dict['rgr_elastic']['model_object'].coef_,                      
                          })#.sort_values(by='coeff', key=abs)

df_coeffs.head(50)
# interestingly, ridge and lasso drove the month to zero. However, may well be because of failure to converge.

             feature  coeff_lin_reg  coeff_ridge  coeff_lasso    coeff_en
0            lag_1hr     638.352926   638.339666   516.018639  516.018639
1            lag_2hr    -152.783812  -152.773036   -15.715497  -15.715497
2            lag_6hr     -62.649848   -62.651050   -72.007198  -72.007198
3            lag_1dy     233.255988   233.258414   259.455191  259.455191
4            lag_1wk     253.831339   253.832090   227.295261  227.295261
5   rolling_mean_1dy     162.308129   162.291819    27.995946   27.995946
6   rolling_mean_1wk    -148.935463  -148.924647    -0.000000   -0.000000
7    rolling_max_1dy      65.315593    65.319703    29.858380   29.858380
8    rolling_max_1wk     -14.885426   -14.889885    -0.000000   -0.000000
9    rolling_min_1dy      31.361448    31.367374    16.216990   16.216990
10   rolling_min_1wk     -11.978699   -11.980078    -0.000000   -0.000000
11   rolling_std_1dy      20.197130    20.200479     0.000000    0.000000
12   rolling_std_1wk     -23.336964   -23.337831     0.000000    0.000000
13              hour      -0.619602    -0.619584     0.000000    0.000000
14       day_of_week       1.271551     1.271551     0.239961    0.239961
15             month       0.522252     0.522258     0.000000    0.000000

In [ ]:
# # check prediction of linear regresison only for now
# y_pred = rgr_ridge.predict(X_test)

# # create df for y_pred
# df_predictions = pd.DataFrame({'y_pred': y_pred, 
#                                'y_true': y_test})

# # get rmse (client by client)
# rmse_by_client = df_predictions.groupby(level='client_id').apply(lambda g: root_mean_squared_error(y_true=g['y_true'], y_pred=g['y_pred']))

In [ ]:
# get mean usage by client (total)
client_mean_usage = df.groupby(level='client_id')['hourly_usage_kwh'].mean()

# compute normalised rmse
nrmse_by_client = rmse_by_client/client_mean_usage

print('mean nrmse: ', nrmse_by_client.mean())
print('nrmse below 0.1: ', nrmse_by_client[nrmse_by_client < 0.1].shape)

mean nrmse:  164.7580806730764
nrmse below 0.1:  (0,)

In [ ]:
# # create quick df of coeffs and feature names in
# df_coeffs = pd.DataFrame({'feature': rgr.feature_names_in_, 
#                           'coeff_lin_reg': rgr.coef_,
#                           'coeff_ridge': rgr_ridge.coef_,
#                           'coeff_lasso': rgr_lasso.coef_,
#                           'coeff_en': rgr_elastic.coef_,                      
#                           })#.sort_values(by='coeff', key=abs)

# df_coeffs.head(50)

             feature  coeff_lin_reg  coeff_ridge  coeff_lasso   coeff_en
0            lag_1hr      65.669317    65.669217    54.861891  32.713592
1            lag_2hr     -12.614988   -12.614901    -0.000000  17.055100
2            lag_6hr     -10.471337   -10.471347    -9.996502  -9.367967
3            lag_1dy      44.726925    44.726933    46.770513  36.478653
4            lag_1wk      43.381046    43.381055    42.922996  36.191526
5   rolling_mean_1dy      15.273485    15.273454     2.093637   4.983043
6   rolling_mean_1wk     -11.688374   -11.688348    -2.092461   0.000000
7    rolling_max_1dy       9.881581     9.881580     8.412378   5.497066
8    rolling_max_1wk       6.571923     6.571911     0.000000   1.753253
9    rolling_min_1dy      -7.654243    -7.654225    -1.706637   0.000000
10   rolling_min_1wk      -5.056458    -5.056462    -5.062610  -1.959985
11   rolling_std_1dy      -4.195199    -4.195179     0.000000   2.195576
12   rolling_std_1wk      -3.478194    -3.478198    -0.044340  -0.000000
13              hour     -20.157968   -20.157964   -16.825581 -19.787694
14       day_of_week       1.515403     1.515402     0.120204   0.501388
15             month     -13.431659   -13.431657   -12.235472  -8.113021