In [1]:
# try to get a simple naive forecast as baseline prediction for electricity demand in future

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, root_mean_squared_error

In [2]:

# aim is to predict electricity demand 24 hours in advance


# naive models to test:

# - just the last observed value (previous hour)
# - same datetime previous day
# - same datetime previous week
# - a window average - use average of the previous week, past month
# - Average of that datetime across all other weeks of dataset


# loss to use: for now use default of MSE
# no need to worry about data leakage etc. with the naive model?

df = pd.read_csv('data/processed/hourly_usage_cleaned.csv')

# drop the unnamed column
df.drop(columns=['Unnamed: 0'], inplace=True)

In [3]:
# try setting datetime and client as index
df_multiindex = df.set_index(['datetime', 'client_id'])

df_multiindex

                               hourly_usage_kwh
datetime            client_id
2012-01-01 01:00:00 1                  4.124365
2012-01-01 02:00:00 1                  4.758883
2012-01-01 03:00:00 1                  4.124365
2012-01-01 04:00:00 1                  4.758883
2012-01-01 05:00:00 1                  4.441624
...                                         ...
2014-12-31 20:00:00 370             8729.729730
2014-12-31 21:00:00 370             8216.216216
2014-12-31 22:00:00 370             8297.297297
2014-12-31 23:00:00 370             7527.027027
2015-01-01 00:00:00 370             6810.810811

[10300015 rows x 1 columns]

In [11]:
# # get the naive forecast for each hour (hourly usage is the target)

# the first naive prediction is just 24 hours prior lag
df_multiindex['yn_1_day_lag'] = df_multiindex.groupby(level='client_id')['hourly_usage_kwh'].shift(24)

# then naive prediciton of one week lag
df_multiindex['yn_1_wk_lag'] = df_multiindex.groupby(level='client_id')['hourly_usage_kwh'].shift(7*24)

# variable for the datetime index for cleaner coding
datetime_index =  pd.to_datetime(df_multiindex.index.get_level_values('datetime'))

# then use mean of that day of week, time and month across all points in dataset
df_multiindex['yn_avg_time_day_month'] =  df_multiindex.groupby([pd.Grouper(level='client_id'),
                                                                 datetime_index.hour,
                                                                 datetime_index.dayofweek,
                                                                 datetime_index.month])['hourly_usage_kwh'].transform('mean')

# drop nan rows (because data where not possible to predict the target can be omitted)
df_multiindex.dropna(inplace=True)

# check that clients have nans where should
df_multiindex.xs(4, level='client_id').head(50)

,hourly_usage_kwh,yn_1_day_lag,yn_1_wk_lag,yn_avg_time_day_month
datetime,,,,
2012-01-09 01:00:00,105.182927,152.439024,109.756098,117.026266
2012-01-09 02:00:00,86.382114,115.345528,97.560976,97.912758
2012-01-09 03:00:00,86.890244,100.101626,95.020325,92.362414
2012-01-09 04:00:00,55.894309,71.138211,65.548780,76.923077
2012-01-09 05:00:00,53.353659,60.467480,61.483740,72.232645
2012-01-09 06:00:00,64.024390,71.138211,68.089431,74.812383
2012-01-09 07:00:00,83.333333,88.414634,94.512195,89.509068
2012-01-09 08:00:00,102.134146,101.626016,106.199187,108.388055
2012-01-09 09:00:00,102.134146,106.199187,104.674797,104.713884
2012-01-09 10:00:00,111.788618,128.556911,107.215447,95.098499
2012-01-09 11:00:00,101.117886,139.735772,105.182927,92.948718
2012-01-09 12:00:00,94.004065,142.784553,130.081301,99.319887
2012-01-09 13:00:00,89.939024,137.703252,132.113821,100.453408
2012-01-09 14:00:00,69.105691,113.313008,108.231707,87.554722
2012-01-09 15:00:00,64.532520,105.691057,105.182927,83.646029
2012-01-09 16:00:00,68.089431,107.215447,100.101626,90.095372
2012-01-09 17:00:00,70.121951,98.069106,107.723577,94.121326
2012-01-09 18:00:00,114.837398,139.735772,152.947154,125.351782
2012-01-09 19:00:00,194.613821,167.174797,208.841463,187.734522
2012-01-09 20:00:00,226.117886,197.154472,226.626016,225.961538
2012-01-09 21:00:00,211.890244,214.430894,219.512195,223.069106
2012-01-09 22:00:00,208.841463,191.565041,208.841463,206.574422
2012-01-09 23:00:00,172.764228,179.878049,194.105691,177.884615
2012-01-10 00:00:00,135.670732,142.276423,168.699187,146.305168
2012-01-10 01:00:00,111.788618,105.182927,128.048780,118.975029
2012-01-10 02:00:00,100.609756,86.382114,103.150407,103.731127
2012-01-10 03:00:00,100.609756,86.890244,90.955285,96.218060
2012-01-10 04:00:00,64.024390,55.894309,55.894309,81.627468
2012-01-10 05:00:00,62.500000,53.353659,57.926829,76.328397
2012-01-10 06:00:00,72.662602,64.024390,63.516260,78.614983
2012-01-10 07:00:00,88.922764,83.333333,87.398374,88.378339
2012-01-10 08:00:00,115.853659,102.134146,112.804878,103.912602
2012-01-10 09:00:00,115.345528,102.134146,110.264228,100.065331
2012-01-10 10:00:00,83.841463,111.788618,95.020325,93.967770
2012-01-10 11:00:00,72.154472,101.117886,94.512195,90.737515
2012-01-10 12:00:00,81.300813,94.004065,104.166667,96.726190
2012-01-10 13:00:00,83.333333,89.939024,95.020325,99.484611
2012-01-10 14:00:00,78.760163,69.105691,99.593496,90.955285
2012-01-10 15:00:00,65.548780,64.532520,88.922764,85.982869
2012-01-10 16:00:00,62.500000,68.089431,80.284553,91.753775
2012-01-10 17:00:00,67.581301,70.121951,97.560976,98.613531
2012-01-10 18:00:00,116.361789,114.837398,134.654472,128.193961
2012-01-10 19:00:00,192.073171,194.613821,201.727642,191.565041
2012-01-10 20:00:00,236.788618,226.117886,229.166667,230.945122
2012-01-10 21:00:00,212.906504,211.890244,222.052846,223.940186
2012-01-10 22:00:00,206.808943,208.841463,224.085366,204.558653
2012-01-10 23:00:00,174.796748,172.764228,212.906504,184.995645
2012-01-11 00:00:00,156.504065,135.670732,158.028455,146.885889
2012-01-11 01:00:00,134.654472,111.788618,118.902439,121.987515
2012-01-11 02:00:00,102.134146,100.609756,103.150407,107.396922

In [12]:
df_multiindex.columns

Index(['hourly_usage_kwh', 'yn_1_day_lag', 'yn_1_wk_lag',
       'yn_avg_time_day_month'],
      dtype='object')

In [13]:
# and now to compute the loss of naive predictions vs the target. For now just use the MSE

#TODO: should pass in each individual client seperately 

# # first get name of columns that are the naive predictions (i.e., all but target)
# naive_pred_cols = df_multiindex.columns[df_multiindex.columns != 'y']

# # Then dictionary containing the MSE values
# naive_forecast_mse_dict = {naive_pred_name: mean_squared_error(y_true=df_multiindex['y'], y_pred=df_multiindex[naive_pred_name]) 
#                            for naive_pred_name in naive_pred_cols}

# naive_forecast_rmse_dict = {naive_pred_name: root_mean_squared_error(y_true=df_multiindex['y'], y_pred=df_multiindex[naive_pred_name]) 
#                            for naive_pred_name in naive_pred_cols}

# get rmse dictionary containing rmse of different naive predictions for each client
predictions = df_multiindex.columns[df_multiindex.columns != 'hourly_usage_kwh']

rmse_dict = {col: df_multiindex.groupby(level='client_id').apply(
    lambda g: root_mean_squared_error(y_true=g['hourly_usage_kwh'], y_pred=g[f'{col}'])) for col in predictions}

# # try compute rmse for each client
# rmse_each_client = df_multiindex.groupby(level='client_id').apply(
#     lambda g: root_mean_squared_error(y_true=g['hourly_usage_kwh'], y_pred=g['yn_1_day_lag']))

# # and compute the mean squared error for each client
# mean_usage_each_client = df_multiindex.groupby(level='client_id').apply(
#     lambda g: mean_squared_error(y_true=g['hourly_usage_kwh'], y_pred=g['yn_1_day_lag']))

In [14]:
# check rmse weighted y the mean of usage of each client
mean_usage_each_client = df_multiindex.groupby(level='client_id')['hourly_usage_kwh'].mean()

In [19]:
nrmse_1week = rmse_dict['yn_1_wk_lag']/mean_usage_each_client
nrmse_1day = rmse_dict['yn_1_day_lag']/mean_usage_each_client
nrmse_1avg = rmse_dict['yn_avg_time_day_month']/mean_usage_each_client


print(nrmse_1week[nrmse_1week < 0.1].shape, '\n')
print(nrmse_1day[nrmse_1day < 0.1].shape, '\n')
print(nrmse_1avg[nrmse_1avg < 0.1].shape, '\n')

nrmse_1week_mean = nrmse_1week.mean()
nrmse_1day_mean = nrmse_1day.mean()
nrmse_1avg_mean = nrmse_1avg.mean()

print(nrmse_1week_mean, '\n')
print(nrmse_1day_mean, '\n')
print(nrmse_1avg_mean, '\n')

(51,)

(100,)

(46,)

0.19071813396120596

0.19750221376834784

0.1849622204294119

client_id
3      2.682209
93     2.074675
94     1.094723
130    1.666578
131    1.335810
132    1.279584
347    1.094126
348    1.254947
366    1.004495
dtype: float64